### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by matthewepler** [geistinteractive/fms-js#10]
Thinking of using on a project for a client but unsure if it's being supported given the time since last update.

**Comment by toddgeist** [comment]
Hi,

I am not using this a lot currently. But nothing in FileMaker has changed so it should still work as always.

I found this to be over-kill for most of what I need so I have made something similar, but more light weight.

https://github.com/geistinteractive/fms-xml-client

**Comment by matthewepler** [comment]
Thanks!
